## Задача 1

Объясняемая переменная y зависит от двух категориальных факторов A и B, причём фактор A имеет 3 уровня, а фактор B - 4 уровня. Результаты наблюдений приведены в таблице:

y = [[2.68, 3.29, 2.88, 4.45],
     [4.12, 4.96, 5.09, 5.22],
     [5.52, 4.50, 5.42, 5.29]]
С помощью двухфакторного дисперсионного анализа проверьте влияние каждого из факторов на переменную y.

=================================================================================================================

In [16]:
import numpy as np
from pprint import pprint

In [3]:
y = np.array([[2.68, 3.29, 2.88, 4.45], [4.12, 4.96, 5.09, 5.22], [5.52, 4.50, 5.42, 5.29]])
y

array([[2.68, 3.29, 2.88, 4.45],
       [4.12, 4.96, 5.09, 5.22],
       [5.52, 4.5 , 5.42, 5.29]])

Для начала посчитаем среднее по всем наблюдениям и средние по градациям факторов А и В. В итоге получим один скаляр и один вектор на 3, второй на 4

In [15]:
y_mean = y.mean()
a_mean = np.array([y[i, :].mean() for i in range(y.shape[0])])
b_mean = np.array([y[:, j].mean() for j in range(y.shape[1])])
pprint(y_mean)
pprint(a_mean)
pprint(b_mean)

4.451666666666666
array([3.325 , 4.8475, 5.1825])
array([4.10666667, 4.25      , 4.46333333, 4.98666667])


Расчитаем квадраты отклонений для фактора А

In [17]:
SSa = y.shape[1] * np.sum((a_mean - y_mean) ** 2)
SSa

7.8407166666666654

Расчитаем квадраты отклонений для фактора B

In [21]:
SSb = y.shape[0] * np.sum((b_mean - y_mean) ** 2)
SSb

1.338166666666669

Рассчитаем квадрат отклонений в целом по наблюдениям

In [24]:
SSt = 0
for i in range(y.shape[0]):
    for j in range(y.shape[1]):
        SSt += (y[i, j] - b_mean[j] - a_mean[i] + y_mean) ** 2
SSt

1.9298833333333327

Посчитаем статистику для фактора А и сразу же проверим гипотезу

In [52]:
a_statistic = (SSa / (y.shape[0] - 1)) / (SSt / (y.shape[0] - 1) * (y.shape[1] - 1))
a_statistic

1.3542643625550195

Посчитаем критическое значение на уровне значимости 0,05

In [53]:
from scipy import stats

In [54]:
stats.f(dfn=y.shape[0] - 1, dfd=y.size - y.shape[0]).ppf(0.95)

4.25649472909375

Как видно посчитанная статистика очень далеко расположена от критического значения. Это значит что мы не можем отвергнуть статистическую гипотезу на принятом уровне значимости. Хотя в целом на с учетом полученных значений доказать что фактор А влияет на переменную нет. Поэтому в данном случае мы принимаем нулевую гипотезу и говорим о том что гарадации фактора А не влияют значимо на нашу переменную.  
Сделаем тоже самое для фактора В.

In [55]:
b_statistic = (SSb / (y.shape[1] - 1)) / (SSt / (y.shape[0] - 1) * (y.shape[1] - 1))
b_statistic

0.15408722653547502

In [56]:
stats.f(dfn=y.shape[1] - 1, dfd=y.size - y.shape[1]).ppf(0.95)

4.06618055135116

Для фактора Б тоже самое, мы не можем отвергнуть нулевую гипотезу. Поэтому ни фактор А ни фактор В не влияют на нашу переменную